FROM shaggycamel/nba.shiny.draft:latest
ENV PORT=7860
EXPOSE 7860
CMD ["Rscript", "-e", "options(shiny.host='0.0.0.0', shiny.port=as.integer(Sys.getenv('PORT','7860'))); library(nba.shiny.draft); nba.shiny.draft::run_app()"]

# This is the huggingface dockerfile. It should live in it's own repo, which is cloned from the huggingface github, but is stored here just as an example. Copy across when needed.
